create table if not exists public.producto_ingrediente (
  id bigint generated by default as identity primary key,
  producto_id bigint not null references public.productos(id) on delete cascade,
  ingrediente_id bigint not null references public.ingredientes(id) on delete restrict,
  created_at timestamptz not null default now(),
  unique (producto_id, ingrediente_id)
);

alter table public.producto_ingrediente enable row level security;

drop policy if exists "anon can read producto ingredientes"
on public.producto_ingrediente;

create policy "anon can read producto ingredientes"
on public.producto_ingrediente
for select
to anon
using (true);

drop policy if exists "authenticated can manage producto ingredientes"
on public.producto_ingrediente;

create policy "authenticated can manage producto ingredientes"
on public.producto_ingrediente
for all
to authenticated
using (true)
with check (true);

-- Ejemplo para relacionar un producto con 3 ingredientes.
-- Cambia los ids por datos reales de tus tablas.
--
-- insert into public.producto_ingrediente (producto_id, ingrediente_id)
-- values
--   (1, 1),
--   (1, 2),
--   (1, 3);
